### ISSUE TITLE
Accepted **kwargs.. how to use them? 

### ISSUE THREAD

**Issue by soliverc** [jzarco/crm-rfm-modeling#5]
```python
            "recency_scoring_method","frequency_scoring_method", and "monetary_scoring_method";
            Set the value of these **kwargs to the following defined scoring methods listed above.
```

These are part of the `fit()` method. What are these for and how can we use them?

**Comment by zark-stark12** [comment]
They are used to decide if you want to build or distribute the values using other methods besides quintiles which is the default method for scoring. Other methods include at the moment are 'mean' and 'median'. 

In future release I will be changing this from passing in a string to passing in the actual function itself.

These other methods however such as mean and median provide a different distribution of splitting the users and scores depending on the distribution of your data. E.g. say your dataset regarding frequency contains a high amount of users who ordered once, using quintiles may not be the best scoring method for scoring Frequency as the results may show using quintiles that it could give a score of 1, 2, or even maybe 3 for users who only ordered once. However using methods such as mean can take the average of the variable and notice that those who only ordered once will be set within a score of 1 rather than distributing it among other scores as well.

These scoring methods depend on your dataset and will need to be investigated by the user before hand to see which scoring method would be suitable if they need to be changed from quintile.
